### ISSUE TITLE
BUG: When the filter entries are empty, and SQLException is being thrown.

### ISSUE THREAD

**Issue by glassyeyedfish** [Macintosh001/EECS-3311-final-project#63]
Basically, when I go into "StockCheckingView" and click "Apply Filter" when the text fields are empty, this is the stack trace for the thrown exception.

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at project.persistence.ProductPersistence.getFilteredProductList(ProductPersistence.java:199)
	at project.logic.StockCheckingLogic.getFilteredList(StockCheckingLogic.java:134)
	at project.display.views.StockCheckingView.lambda$new$0(StockCheckingView.java:80)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
```

**Comment by LJWoolner** [comment]
The problem was with the initialization of the filterString. This has now been fixed.
